### ISSUE TITLE
wxml报错

### ISSUE THREAD

**Issue by cz848** [Cap32/wxml-loader#1]
运行webpack报错
ERROR in ./src/pages/detail/detail.wxml
Module not found: Error: Can't resolve '../../icons/{{icons[key]}}.svg' in '……/src/pages/detail'
 @ ./src/pages/detail/detail.wxml
跟路径无关，好像是不能识别{{icons[key]}}，也不知道是不是此插件造成的，能否帮忙定位一下？

**Comment by Cap32** [comment]
确实是因为不能识别 `{{icons[key]}}` 导致的问题，webpack 在编译时无法知道 `{{icons[key]}}` 的值。

暂时想到的妥协方案是不处理动态引入（含`{{}}`的路径），用户自己通过 `copy-webpack-plugin` 之类的插件 copy 引用的文件到 dist 目录。

**Comment by cz848** [comment]
那就不能压缩文件了是吧

**Comment by Cap32** [comment]
我发布了新版，不处理动态引入的资源文件 3ea5c69584549b9169b9c745a003f94b1da20a95 ，使 webpack 不报错。

这只是一个妥协的临时解决方案，周末有空会完善一个更好的解决方案。😁

**Comment by Cap32** [comment]
压缩问题，可以先用微信开发者工具自带的压缩功能，问题不大

**Comment by cz848** [comment]
OK，非常感谢

**Comment by hsg965** [comment]
resolve.alias定义的图片别名也没办法解析码？
