### ISSUE TITLE
设置了pulicPath 后静态资源前缀会增加 ./

### ISSUE THREAD

**Issue by xierenyuan** [Cap32/wxml-loader#10]
hi。
我现在 希望做build 的时候 把静态资源自动上传到七牛云去,  设置了webapck publicPath 后发现生成
代码前缀 发现前面 带了./  调试后发现 是wxml-loader那边有处理  看能否加一个开关 人为控制是否 需要加./
![image](https://user-images.githubusercontent.com/7599351/41777254-4b70fdce-765d-11e8-8b55-20303aebd0b6.png)
![image](https://user-images.githubusercontent.com/7599351/41777261-51f486f2-765d-11e8-8548-6f222e7def3e.png)

**Comment by Cap32** [comment]
这是一个 bug，已修复 c5e477de2055a9a5b630a4c6f1820f0fa4e99f21 并发布至 npm

Thanks
