### ISSUE TITLE
WXS 文件不能引入

### ISSUE THREAD

**Issue by sin-ning** [Cap32/wxml-loader#4]
WXML 中映入 WXS 文件。

**Comment by Cap32** [comment]
请提供重现代码

**Comment by sin-ning** [comment]
> 正确的

`<wxs src="../tools.wxs" module="tools" />`

> 处理后的 （wxs 不能绝对路径，要相对路径）

`<wxs src="/components/tools.wxs" module="tools" />`

**Comment by Cap32** [comment]
wxml 里面所引用和生成的路径，是 [file-loader](https://github.com/webpack-contrib/file-loader) 或之类的 loader 负责的事情 （下面例子以 file-loader 为例）。

例子上，wxml-loader 对于 wxs 文件仅做了的事情是提取 `../tools.wxs` 这个引用的资源路径，然后把路径交给 webpack 或相应 loader 处理，处理完之后写入新资源路径到 wxml-loader。

如果你熟悉 webpack 开发 web 前端的话，wxml-loader 就像 css-loader。.css 文件里可能会 `background: url(../my.png)`，css-loader 仅负责提取 `../my.png`，然后再通过 file-loader 来处理 `../my.png`，输出路径也是通过  file-loader 的配置来完成。

关于 `.wxs` 的 file-loader 配置问题，建议参考 https://github.com/cantonjs/wxapp-boilerplate ，里面file-loader 配置是相对路径输出。

**Comment by Cap32** [comment]
若仍有问题，可以 reopen 这个 issue

**Comment by sin-ning** [comment]
Thanks
