### ISSUE TITLE
编译form map 最小化导致属性丢失

### ISSUE THREAD

**Issue by qwlong** [Cap32/wxml-loader#8]
编译form变成了这个样子
```
<form bindsubmit="submitForm" report-submit="true">
to
<form report-submit="">
```
编译map变成了这样子
```
<map id="map" controls="{{controls}}"></map>
to
<map id="map" controls></map>
```

**Comment by Cap32** [comment]
to?

**Comment by qwlong** [comment]
这个是直接粘贴了，没有显示全，弄成代码的样子OK了

All html-minifier options are supported
应该是 html-minifier导致的，我测试了好几次，都不行

然后最后我把  minimize 改为 false 可以了
但是这个的确是一个问题，不能直接压缩wxml的代码了

我觉得，可以直接进行去空格压缩，而不处理wxml上面的属性值，会不会能够很好的解决问题

**Comment by Cap32** [comment]
感谢反馈。html-minifier 不仅仅是 minify，而且会修改 attributes，甚至调整文档结构，而且暂时没办法禁止（至少我暂时找不到方法），这实在不太理想。

不过其实把 miniize 设为 false，改用微信开发者工具自带的压缩功能也可以。

**Comment by jaceechan** [comment]
fixed https://github.com/Cap32/wxml-loader/releases/tag/v0.1.2
