### ISSUE TITLE
build后，wxml内的属性的驼峰被被改成了小写

### ISSUE THREAD

**Issue by fengbaozhiling** [Cap32/wxml-loader#9]
`    <user avatarUrl="{{userInfo.avatarUrl}}" nickName="{{userInfo.nickName}}"></user>
`

＝》

`<user avatarurl="{{userInfo.avatarUrl}}" nickname="{{userInfo.nickName}}"></user>`

nickname原本是驼峰的

**Comment by jaceechan** [comment]
fixed https://github.com/Cap32/wxml-loader/releases/tag/v0.1.2
